# Generated by Django 3.1.7 on 2021-03-28 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=200)),
                ('localencontrado', models.CharField(max_length=50)),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='image/')),
                ('status', models.CharField(choices=[('Perdido', 'Perdido'), ('Encontrado', 'Encontrado')], max_length=15, verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
